#!name=colorweather
#!desc=colorweather

[URL Rewrite]

^https:\/\/ad\.caiyunapp\.com\/ - reject

[Script]

cytq = type=http-response, pattern=^http[s]?:\/\/biz\.(caiyunapp|cyapi)\.(com|cn)\/v2\/user.*$, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/WeiRen0/Scripts/main/cytq.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% *.caiyunapp.*,*cyapi*
