#!url= https://raw.githubusercontent.com/onlynair/jd_scripts/master/Surge/boxjs.module
#!name=BoxJs
#!desc=http://boxjs.com

[General]
force-http-engine-hosts = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net

[Script]
Rewrite: BoxJs = type=http-request,pattern=^https?:\/\/(.+\.)?boxjs\.(com|net),script-path=https://raw.githubusercontent.com/onlynair/jd_scripts/master/backUp/chavy.boxjs.js, requires-body=true, timeout=120

[MITM]
hostname = %INSERT% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net
